version: "3.3"

services:
  laravel-prod:
    build:
      context: .
      args:
        DEFLAUNT_PHP_VERSION: $DEFLAUNT_PHP_VERSION
    container_name: laravel_prod
    working_dir: /var/www/app
    volumes:
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    # ports:
    #   - $NGINX_PORT:8080
    #   - 443:443
